name: Deploying Terraform to AWS
run-name: ${{ github.actor }} is Deploying infrastructure to AWSğŸš€
on: [push]
jobs:
  Deploy-terraform-aws:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner d."
      - name: Installing Terraform CLI 
        uses: hashicorp/setup-terraform@v3
      - name: Run terraform and deploy the code to AWS
        run: |
          ls ${{ github.workspace }}
          export AWS_ACCESS_KEY_ID=${{ secrets.WS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          terraform init
          terraform fmt
          terraform apply -auto-approve
      - run: echo "ğŸ This job's status is ${{ job.status }}."